[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#E0729B"
backgroundColor = "#FDEEF5"
secondaryBackgroundColor = "#FFCFE2"
textColor = "#6E5A68"
font = "sans serif"
